[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.pylsp.config.pylsp.plugins.ruff]
enabled = true

[[language]]
name = "python"
language-servers = ["ruff", "pylsp"]
auto-format = true
